// tools/expansions.js
// Two extra paragraphs per article, per locale — new facts, not padding.
// Applied by tools/apply-expansions.js, spliced in just before each
// article's closing paragraph, to bring every piece closer to ~1,000 words.
'use strict';

const EXPANSIONS = {
  en: {
    'japan-nose-blowing': [
`This isn't unique to Japan, either, though the intensity varies. Neighboring South Korea and parts of China share a milder version of the same discomfort around loud nose-blowing, while placing less emphasis on the mask-as-social-buffer that Japan developed so distinctly. What sets Japan apart is how deliberately the mask became a piece of etiquette equipment long before the COVID-19 pandemic made surgical masks a global habit — for Japanese commuters, the pandemic simply exported to the rest of the world a barrier they'd already been using for decades.`,
`Generational change is slowly nudging the rule, though not erasing it. Surveys of younger, urban Japanese show a slightly more relaxed attitude toward nose-blowing in casual settings among close friends, even if the norm remains ironclad on public transport and in the workplace. Etiquette guides aimed at foreign residents still list it as one of the first rules to learn, right alongside not eating while walking and speaking quietly on the phone in public — proof that, decades on, the custom shows no sign of disappearing.`
    ],
    'india-sacred-cow': [
`The cow's economic importance took on a modern, secular dimension in the 20th century with India's so-called White Revolution, launched in the 1970s around the dairy cooperative Amul. The program turned India into the world's largest milk producer within a few decades, built almost entirely on small farmers who often kept just one or two cows each. In that sense, the animal's sacred status and its role as a genuine economic lifeline for millions of rural households reinforce each other rather than competing.`,
`Politically, cow protection remains one of India's more contentious issues. Several states have tightened anti-slaughter laws in recent years, in some cases extending prison sentences for violations, while vigilante groups claiming to protect cows have occasionally clashed with beef traders and transporters, drawing criticism from human rights organizations. The debate cuts across religion, caste, and regional identity, making the cow not just a spiritual symbol but, at times, a genuinely divisive political one.`
    ],
    'finland-sauna-queue': [
`Part of the ritual many visitors miss entirely is the *vihta* (or *vasta*, depending on the region) — a bundle of fresh birch branches gently swatted against the skin during the hottest part of the sauna session. Far from being punishment, Finns describe the light sting as invigorating: it's said to improve circulation and leave behind the faint, distinctive scent of birch that lingers in Finnish saunas from June through August, when the branches are harvested and either used fresh or frozen for the rest of the year.`,
`Sauna diplomacy isn't just an old story, either. Finnish presidents and prime ministers have hosted foreign counterparts in saunas built specifically for state visits, and Finland's embassy saunas abroad — including one in Washington, D.C. — are regularly used to host guests in an atmosphere considered more relaxed and candid than any conference room. The idea is simple: it's harder to stay guarded, diplomatically speaking, once everyone's sweating in a towel.`
    ],
    'south-korea-age-system': [
`Part of why the traditional system endured so long has to do with Confucian values still embedded in Korean social life, where age directly determines how people address each other, who speaks first, and even who pours the drinks at dinner. Being a year "older" under the Korean system could subtly shift these dynamics, which is one reason many older Koreans felt genuine attachment to the traditional count even as younger generations pushed for simplification.`,
`The three-system confusion also spilled into pop culture and international media for years, with K-pop idols' ages frequently reported inconsistently across Korean and international outlets, occasionally sparking online debate among fans trying to figure out someone's "real" age. Since the 2023 reform, entertainment agencies and official biographies now default to international age, one small but telling sign of how the law reached even the country's most globally visible export.`
    ],
    'france-restaurant-bill': [
`This unhurried approach also shows up in the enduring popularity of the *menu du jour* — a fixed, multi-course menu changed daily, often the best value on the card — which encourages diners to settle in for the full sequence of courses rather than grab a quick single plate. Ordering à la carte and leaving after one dish is technically fine, but it runs against the grain of a meal structure designed, from the start, to unfold slowly.`,
`The contrast with American dining culture is instructive: in the United States, where tipping can make up the bulk of a server's income, turning tables quickly is a direct financial incentive, and the culture of "check please" as soon as plates are cleared reflects that pressure. Remove the tipping incentive, as France effectively does through its included-service model, and the entire logic of rushing diners along simply disappears.`
    ],
    'mexico-day-of-the-dead': [
`Pixar's 2017 film Coco introduced the tradition to a global audience that had, until then, mostly encountered Día de Muertos through Halloween-adjacent imagery. The film's depiction of the ofrenda, the marigold path, and the idea that the dead are forgotten only when no living person remembers them anymore struck such a chord that visits to Mexican Day of the Dead events reportedly increased in the years that followed, particularly among international tourists eager to see the real celebration behind the animated one.`,
`Some of the most striking celebrations happen away from the big-city parades: on the chinampas (floating gardens) of Mixquic, near Mexico City, candlelit cemeteries draw visitors overnight, while on the island of Janitzio in Michoacán, Purépecha communities paddle canoes lit with candles across Lake Pátzcuaro to reach the island's cemetery, in a ritual largely unchanged for generations and considered one of the most moving versions of the tradition anywhere in the country.`
    ],
    'netherlands-no-curtains': [
`The custom isn't perfectly uniform across the country: residents of larger cities like Amsterdam and Rotterdam, especially in areas that have seen more burglaries or simply more foot traffic from tourists, have grown somewhat more likely to use sheer curtains or blinds than their counterparts in small towns and villages, where the old openness remains closer to the norm. Rising awareness of home security and, more recently, concerns about being filmed or photographed without consent have added new, practical reasons to reconsider a centuries-old habit.`,
`The tradition of window decoration even has an informal name in Dutch — *etaleren*, borrowed from the word for a shop display — used half-jokingly to describe how seriously some households take arranging plants, ornaments, and seasonal decorations in their front window for the entire street to admire. Estate agents have noted that a well-dressed window can even give a subtle positive impression during a home sale, further reinforcing why so few residents feel any urge to hide it behind fabric.`
    ],
    'thailand-sacred-head': [
`The same bodily hierarchy runs through the *wai*, Thailand's palms-together greeting, where the height at which the hands are raised — and who bows first and lowest — is calibrated precisely to the relative age, status, and seniority of the two people greeting each other. A student greeting a teacher, or a young person greeting an elder, raises their joined hands notably higher than someone greeting a peer, a small daily reenactment of the same respect logic that keeps hands away from anyone's head.`,
`The reverence for the head connects, too, to one of Thai Buddhism's most widespread customs: temporary monkhood. Most Thai Buddhist men are expected to ordain as monks for some period in their life, even just a few weeks, and the ceremony begins with shaving the head completely — a profound act of renunciation that only makes sense once you understand just how much cultural and spiritual weight that part of the body carries in the first place.`
    ],
    'germany-splitting-bills': [
`Some historians trace the modern intensity of this habit to the postwar decades, when West Germany's rapid reconstruction leaned heavily on a cultural narrative of individual responsibility and self-reliance — the idea that each person should account for exactly what they consumed became almost a civic virtue, extending naturally from the factory floor to the dinner table. Whether or not that historical account fully explains the custom, it fits neatly with the broader German preference for explicit rules over unspoken social expectations.`,
`Dating culture is where the custom generates the most debate, even among Germans themselves: while friends splitting a bill is virtually unquestioned, some younger Germans have pushed back against strict getrennte Kasse on early dates, arguing it can feel transactional rather than romantic. Online forums and advice columns dedicated to modern German dating regularly debate the question, suggesting the old rule, while still dominant, is no longer entirely uncontested.`
    ],
    'ethiopia-calendar': [
`The gap between calendars produced one unforgettable moment in 2007, when Ethiopia marked its own turn of the millennium — celebrating the year 2000 on the Ethiopian calendar a full seven years after the rest of the world had already done so. The government launched a major international tourism campaign around the event, complete with a purpose-built convention center in Addis Ababa, hoping to draw global attention to the country's singular relationship with time.`,
`In practice, Ethiopians navigate both calendars daily without much friction: banks print statements with both dates, smartphones sold in the country often include Ethiopian calendar apps as a default alongside the Gregorian one, and government offices routinely stamp documents with dual dates to avoid confusion for anyone dealing with international partners. Far from being an inconvenience, most Ethiopians describe the dual system as simply how time has always worked.`
    ],
    'italy-cappuccino-rule': [
`The modern Italian coffee bar as we know it is a relatively recent invention: it took shape after 1948, when Achille Gaggia patented a machine that used a spring-piston lever to force water through coffee at high pressure, creating the crema that defines a proper espresso to this day. Before Gaggia's machine spread through Italian cafés in the 1950s, the sharp morning-versus-afternoon coffee etiquette that exists today hadn't fully crystallized — the cappuccino rule, in other words, is a 20th-century tradition, not an ancient one.`,
`Naples has its own distinct twist on coffee culture worth knowing: the *caffè sospeso*, or "suspended coffee," a practice where a customer pays for two espressos but only drinks one, leaving the second paid-in-advance for a stranger who can't afford it. The custom, born in Naples's working-class cafés in the mid-20th century, has been revived in recent years by coffee shops around the world inspired by the idea, proving Italian coffee culture exports more than just the cappuccino rule.`
    ],
    'norway-babies-outside': [
`The cultural gap this practice can create became international news in 1997, when a Danish mother visiting New York left her sleeping baby in a stroller outside a restaurant window she could see from her table — standard practice back home — and was arrested for child endangerment. The case made headlines across Scandinavia and the United States, and became a textbook example of how a completely unremarkable habit in one culture can look like negligence in another; the charges were eventually dropped.`,
`Nordic pediatric associations have generally continued to support outdoor napping in cold weather for healthy infants, provided they're dressed appropriately and monitored nearby, though most guidelines now recommend keeping a baby monitor or clear sightline rather than leaving a stroller fully out of view. The practice has also drawn renewed academic interest in recent years, with researchers studying whether the reported sleep benefits hold up under controlled conditions rather than just parental impression.`
    ],
    'china-number-four': [
`International companies have learned this lesson the hard way more than once: Nokia reportedly skipped the number four when naming several phone lines sold in Asian markets, and other electronics makers have quietly avoided model numbers containing four for the same reason. The avoidance isn't limited to consumer products — apartment listings, business names, and even corporate registration numbers get adjusted where possible to sidestep the unlucky digit.`,
`On the flip side, phone numbers and license plates loaded with lucky digits like eight can fetch extraordinary prices at auction: plate and phone-number auctions in China and Hong Kong have recorded sales in the hundreds of thousands of dollars for numbers dense with eights, while sequences containing multiple fours are often sold at a discount or go unsold entirely. The number itself carries real, measurable market value — a rare case of superstition showing up directly on a price tag.`
    ],
    'argentina-mate-sharing': [
`While the ritual is most associated with Argentina, mate is just as central to daily life in Uruguay — which actually has the highest per-capita mate consumption in the world — and in Paraguay, where a cold version called *tereré* is preferred in the country's punishing summer heat. Southern Brazil, particularly the state of Rio Grande do Sul, shares the same gaucho-rooted mate culture, proof that the ritual belongs to a shared regional identity that predates the modern national borders drawn across it.`,
`Mate has also gone mobile: it's now common to see Argentines walking down the street balancing a mate gourd in one hand and a thermos tucked under the other arm, refilling on the go between errands. Global visibility got a boost from athletes like footballer Lionel Messi and rugby players routinely sipping mate on camera during international tournaments, turning a very local ritual into something millions of foreign fans now recognize on sight, even if they've never tasted it.`
    ],
    'bhutan-happiness-index': [
`Bhutan's relationship with modernity has been deliberately gradual: television and the internet weren't legally introduced until 1999, making it one of the last countries on Earth to connect to global broadcast media. The king at the time framed the delay explicitly in terms of Gross National Happiness, arguing the country needed time to weigh the benefits of connectivity against its potential to disrupt social cohesion and traditional culture — a rare case of a government consciously slow-walking technology for stated wellbeing reasons.`,
`The happiness narrative also has a genuinely dark chapter critics regularly point to: in the early 1990s, Bhutan stripped citizenship from and expelled tens of thousands of ethnic Nepali-speaking Lhotshampa residents, many of whom spent decades in refugee camps in Nepal before being resettled, mostly in Western countries. Bhutanese officials have rarely addressed the episode directly, and it remains one of the clearest examples of how a country's official wellbeing philosophy can coexist uneasily with real human rights failures.`
    ],
    'russia-no-smiling': [
`Some researchers trace the custom's modern intensity to the hardships of the Soviet era, when public displays of unearned positivity could seem naive or even suspicious in a system defined by scarcity, surveillance, and hardship — smiling without a clear, honest reason simply didn't match daily reality for generations of Russians. That historical backdrop reinforced older folk beliefs about smiling's meaning, hardening a cultural pattern that persisted well after the political system that shaped it disappeared.`,
`That said, the custom is visibly shifting in one specific arena: customer service. Since the 1990s, as Western-style retail, hospitality, and airline brands expanded into Russia, many companies have explicitly trained staff to smile at customers as part of international service standards, creating an unusual split where a barista or flight attendant might smile professionally while a stranger on the same street would never do so without a real reason — two competing scripts for the same gesture, operating side by side.`
    ],
    'portugal-codfish': [
`One of the most beloved bacalhau dishes, *bacalhau à Brás* — shredded cod mixed with thin fried potato straws, scrambled egg, and black olives — is said to have been invented in the Bairro Alto district of Lisbon by a tavern owner known only as "Brás," sometime in the 19th century. The dish has since become so ubiquitous that most Portuguese households have their own family variation, and disputes over whose version is the "correct" one remain a genuinely popular topic of debate at the dinner table.`,
`The modern irony of Portugal's cod obsession runs deeper than most diners realize: overfishing collapsed Atlantic cod stocks so severely over the 20th century that Portugal today imports essentially all the bacalhau it consumes, almost entirely from Norway and Iceland. A country's defining national dish, in other words, depends entirely on fish caught thousands of kilometers away in someone else's waters — a supply chain that has held steady for centuries despite wars, dictatorships, and the collapse of Portugal's own historic fishing fleet.`
    ],
    'philippines-big-families': [
`One of the most visible everyday expressions of this family devotion is the *balikbayan* box — large cardboard boxes packed with goods, snacks, and gifts that overseas Filipino workers ship home, sometimes months in advance of a visit, to relatives across the extended family tree. Entire businesses exist just to consolidate and ship these boxes affordably, and their arrival is often treated as a small family event in itself, unpacked together with genuine excitement over foreign chocolate, brand-name shoes, or vitamins that are pricier back home.`,
`Filipino godparent culture, or *compadrazgo*, takes the extended-family principle even further: it's common for a baptism or wedding to have not one or two godparents but a dozen or more, each expected to play an active role in the child's or couple's life going forward. Far from a symbolic formality, being asked to serve as a godparent carries real, lasting social obligations — another thread in the dense web of mutual support that defines Filipino family life.`
    ],
    'switzerland-punctual-trains': [
`The engineering behind this precision is best seen at Zurich's main station, Zurich HB, one of the busiest rail hubs in Europe, where dozens of trains arrive and depart within the same few minutes every hour, timed so that passengers can cross the platform and catch a connecting train with as little as two or three minutes to spare. That kind of synchronization requires planning trains not as individual routes but as one interlocking national system, recalculated to the second whenever a single line changes its schedule.`,
`The contrast with neighboring Germany is often cited as the clearest proof of how much culture and investment matter here: Deutsche Bahn, Germany's national railway, has struggled for years with chronic delays and infrastructure backlogs despite operating in a country with comparable wealth and engineering capability. Swiss and German commentators alike frequently point to the comparison as evidence that punctuality is a choice sustained by consistent funding and cultural expectation, not an automatic byproduct of being a wealthy, orderly country.`
    ],
    'morocco-haggling': [
`The mint tea offered during negotiations carries its own nickname among visitors and even some Moroccans: "Berber whiskey," a playful nod to how central the drink is to hospitality in a country where alcohol is far less present in social life. Prepared with green tea, generous handfuls of fresh mint, and a notable amount of sugar, and traditionally poured from a height to create a light foam on top, the tea ritual isn't just a sales tactic — refusing it outright, even when not planning to buy anything, can feel like a small social rejection in its own right.`,
`Modern Morocco increasingly runs on two parallel commercial systems: fixed-price supermarkets, shopping malls, and chain stores, especially common in newer neighborhoods of Casablanca and Rabat, operate exactly like their European counterparts, with no haggling expected or welcome. Traditional souks and independent shops, meanwhile, still run almost entirely on negotiation. Younger, urban Moroccans move fluidly between both systems, adjusting their expectations instantly depending on which kind of storefront they walk into.`
    ],
    'iceland-no-surnames': [
`Iceland's Naming Committee, the Mannanafnanefnd, doesn't just rubber-stamp new names — it actively rejects proposals that don't conform to Icelandic grammar and spelling rules, a process that has occasionally made international news. Parents have taken the committee to court over rejected names, and in a notable 2013 case, a teenager named Blær ("light breeze") successfully sued to keep a name officials had initially ruled grammatically invalid for a girl, winning the right to use it legally for the first time.`,
`The first-name-only culture runs so deep that it applies even at the very top: Icelanders commonly refer to their president or prime minister by first name alone, in official contexts and casual conversation alike, without it reading as disrespectful the way it might elsewhere. It's a small but telling sign of just how thoroughly the patronymic system shapes not only how Icelanders are named, but how flat and informal the country's entire social hierarchy tends to feel by comparison.`
    ],
    'greece-breaking-plates': [
`The exclamation "Opa!," shouted at the moment a plate shatters or a dancer leaps, has become one of Greece's most recognizable cultural exports, largely thanks to Greek diaspora restaurants across the United States, Australia, and Europe that kept the plate-smashing spirit alive — sometimes literally, sometimes with the safer flower-and-napkin substitute — long after it faded from everyday practice back home. For many people outside Greece, "Opa!" is the single word most associated with Greek culture, entirely disconnected from its original ritual context.`,
`Regional variations add further texture to the custom: in Crete, celebratory gunfire sometimes accompanies weddings and baptisms in rural areas instead of or alongside plate-breaking, while in Cyprus, a similar spirit of exuberant celebration goes by the word *glentia*, with its own local customs around music, dancing, and communal joy. Across the Greek-speaking world, the specific ritual changes from island to island, but the underlying impulse — that real joy demands a physical, shared outlet — stays remarkably consistent.`
    ],
    'singapore-chewing-gum-ban': [
`The gum ban is really just the most famous entry in a much longer list of rules that earned Singapore its half-joking nickname, "the fine city": eating or drinking on the MRT can cost a fine of several hundred Singapore dollars, carrying durian fruit on public transport is banned outright because of its notoriously strong smell, and jaywalking, failing to flush a public toilet, or feeding pigeons can all technically result in a fine. Taken together, these rules reflect the same underlying philosophy as the gum ban: public space is treated as a shared resource worth protecting through strict, consistently enforced rules.`,
`The chewing gum ban became such a well-known symbol of Singaporean strictness that it regularly turns up in international media and comedy as shorthand for the country's reputation for order — often exaggerated into the false claim that chewing gum itself, not just its sale, is illegal. Singaporean officials have occasionally pushed back publicly against the most exaggerated versions of the story, pointing out that the actual rule is far narrower than its global reputation suggests, even if the country has clearly made peace with owning the joke.`
    ],
    'peru-guinea-pig': [
`Peru is, by a wide margin, the world's leading producer and consumer of guinea pigs as food, raising an estimated 22 million of them a year, mostly on small family farms across the Andean highlands. In recent decades, some producers have tried to modernize cuy farming and even explored export markets to Peruvian communities abroad in the United States and Europe, though the animal's continued cultural association with pets in most of the world has limited its appeal as a mainstream export product outside specialty and nostalgia markets.`,
`The tradition isn't uniquely Peruvian, either: neighboring Ecuador and Bolivia share the same Andean culinary heritage, each with its own regional preparations and names — *cuy* in Ecuador closely mirrors Peru's version, while some Bolivian communities favor different spicing and cooking methods. Across all three countries, the guinea pig's role traces back to the same pre-Inca domestication history, making it one of the oldest continuously farmed food animals in the Americas, predating the arrival of chickens, pigs, or cattle by thousands of years.`
    ],
    'sweden-fika': [
`Fika even has its own unofficial national holiday: October 4th is celebrated across Sweden as *Kanelbullens dag*, "Cinnamon Bun Day," created in 1999 by a bakers' trade association to promote the classic fika pastry. What started as a marketing campaign has become a genuine cultural fixture, with cafés, offices, and home bakers across the country marking the day with an extra round of cinnamon buns — proof of how easily a commercial idea can take root when it slots neatly into an already-beloved ritual.`,
`Fika is often mentioned in the same breath as the Danish concept of *hygge*, and the two get lumped together internationally as generic "Scandinavian coziness," but they aren't quite the same thing. Hygge leans toward a broader feeling — candlelight, blankets, a sense of warm contentment that can happen alone or with others, at any time. Fika is more specific and social: a scheduled pause, almost always shared, built around coffee and a small sweet, with its own unwritten rules about when and how it happens during the working day.`
    ]
  },

  es: {
    'japan-nose-blowing': [
`Esto tampoco es exclusivo de Japón, aunque la intensidad varía. Corea del Sur y algunas zonas de China comparten una versión más suave de esa misma incomodidad hacia el sonarse fuerte, aunque le dan menos peso al papel de la mascarilla como barrera social que Japón desarrolló de forma tan particular. Lo que distingue a Japón es lo deliberadamente que la mascarilla se convirtió en una pieza de etiqueta mucho antes de que la pandemia de covid-19 la volviera un hábito global: para los viajeros japoneses, la pandemia simplemente exportó al resto del mundo una barrera que ellos ya usaban desde hacía décadas.`,
`El cambio generacional está suavizando la norma poco a poco, aunque sin borrarla. Las encuestas entre japoneses jóvenes y urbanos muestran una actitud algo más relajada hacia sonarse la nariz en entornos informales entre amigos cercanos, aunque la norma sigue siendo inquebrantable en el transporte público y en el trabajo. Las guías de etiqueta dirigidas a residentes extranjeros siguen incluyéndola entre las primeras reglas que hay que aprender, junto con no comer mientras se camina o hablar bajito por teléfono en público: prueba de que, décadas después, la costumbre no muestra ninguna señal de desaparecer.`
    ],
    'india-sacred-cow': [
`La importancia económica de la vaca adquirió una dimensión moderna y laica en el siglo XX con la llamada Revolución Blanca de India, lanzada en la década de 1970 alrededor de la cooperativa lechera Amul. El programa convirtió a India en el mayor productor de leche del mundo en pocas décadas, construido casi por completo sobre pequeños agricultores que a menudo tenían solo una o dos vacas cada uno. En ese sentido, el estatus sagrado del animal y su papel como sustento económico real para millones de hogares rurales se refuerzan mutuamente en lugar de contradecirse.`,
`Políticamente, la protección de la vaca sigue siendo uno de los temas más delicados de India. Varios estados han endurecido en los últimos años sus leyes contra el sacrificio, en algunos casos ampliando las penas de prisión por infringirlas, mientras que grupos autoproclamados protectores de vacas se han enfrentado ocasionalmente con comerciantes y transportistas de carne, generando críticas de organizaciones de derechos humanos. El debate atraviesa religión, casta e identidad regional, convirtiendo a la vaca no solo en un símbolo espiritual, sino, a veces, en un símbolo político genuinamente divisivo.`
    ],
    'finland-sauna-queue': [
`Parte del ritual que muchos visitantes pasan por alto es el *vihta* (o *vasta*, según la región): un manojo de ramas frescas de abedul que se golpea suavemente contra la piel durante la parte más calurosa de la sesión de sauna. Lejos de ser un castigo, los finlandeses describen ese ligero escozor como revitalizante: se dice que mejora la circulación y deja un aroma tenue y característico a abedul que impregna las saunas finlandesas entre junio y agosto, cuando se cosechan las ramas y se usan frescas o congeladas para el resto del año.`,
`La diplomacia de la sauna tampoco es solo una anécdota antigua. Presidentes y primeros ministros finlandeses han recibido a homólogos extranjeros en saunas construidas específicamente para visitas de Estado, y las saunas de las embajadas finlandesas en el extranjero —incluida una en Washington D.C.— se usan con regularidad para recibir invitados en un ambiente considerado más relajado y sincero que cualquier sala de reuniones. La idea es simple: es más difícil mantenerse a la defensiva, diplomáticamente hablando, cuando todos están sudando envueltos en una toalla.`
    ],
    'south-korea-age-system': [
`Parte de por qué el sistema tradicional perduró tanto tiempo tiene que ver con los valores confucianos que siguen arraigados en la vida social coreana, donde la edad determina directamente cómo se dirigen las personas entre sí, quién habla primero e incluso quién sirve las bebidas en una cena. Ser un año "mayor" bajo el sistema coreano podía alterar sutilmente estas dinámicas, una de las razones por las que muchos coreanos mayores sentían un apego genuino al conteo tradicional incluso cuando las generaciones más jóvenes pedían simplificarlo.`,
`La confusión de los tres sistemas también se filtró durante años a la cultura pop y a los medios internacionales, con las edades de los ídolos del K-pop reportadas de forma inconsistente entre medios coreanos e internacionales, lo que a veces generaba debates en redes entre fans tratando de averiguar la edad "real" de alguien. Desde la reforma de 2023, las agencias de entretenimiento y las biografías oficiales usan por defecto la edad internacional, una señal pequeña pero reveladora de cómo la ley llegó incluso a la exportación cultural más visible del país en el mundo.`
    ],
    'france-restaurant-bill': [
`Este enfoque sin prisas también se refleja en la persistente popularidad del *menu du jour*: un menú fijo de varios platos que cambia a diario, a menudo la mejor relación calidad-precio de la carta, y que invita a los comensales a instalarse para toda la secuencia de platos en lugar de pedir uno solo rápidamente. Pedir a la carta e irse después de un plato es técnicamente aceptable, pero va en contra de una estructura de comida diseñada, desde el principio, para desarrollarse con calma.`,
`El contraste con la cultura gastronómica estadounidense resulta revelador: en Estados Unidos, donde las propinas pueden constituir la mayor parte del ingreso de un camarero, rotar las mesas rápido supone un incentivo económico directo, y la costumbre de pedir la cuenta apenas se retiran los platos refleja esa presión. Elimina el incentivo de la propina, como hace Francia en la práctica con su modelo de servicio incluido, y toda la lógica de apurar a los comensales simplemente desaparece.`
    ],
    'mexico-day-of-the-dead': [
`La película de Pixar Coco (2017) presentó la tradición a una audiencia global que, hasta entonces, solía conocer el Día de Muertos sobre todo a través de imágenes asociadas a Halloween. La forma en que la película retrata la ofrenda, el camino de cempasúchil y la idea de que un difunto solo se olvida de verdad cuando nadie vivo lo recuerda ya caló tan hondo que, según reportes, las visitas a celebraciones mexicanas del Día de Muertos aumentaron en los años siguientes, sobre todo entre turistas internacionales interesados en ver la celebración real detrás de la versión animada.`,
`Algunas de las celebraciones más impactantes ocurren lejos de los grandes desfiles urbanos: en las chinampas de Mixquic, cerca de Ciudad de México, los cementerios iluminados con velas reciben visitantes durante toda la noche, mientras que en la isla de Janitzio, en Michoacán, comunidades purépechas reman en canoas iluminadas con velas a través del lago Pátzcuaro para llegar al cementerio de la isla, en un ritual apenas modificado durante generaciones y considerado una de las versiones más conmovedoras de la tradición en todo el país.`
    ],
    'netherlands-no-curtains': [
`La costumbre no es perfectamente uniforme en todo el país: los residentes de ciudades grandes como Ámsterdam o Róterdam, sobre todo en zonas con más robos o simplemente más tránsito de turistas, se han vuelto algo más propensos a usar visillos o persianas que sus vecinos de pueblos pequeños, donde la apertura tradicional sigue más cercana a la norma. La creciente conciencia sobre seguridad doméstica y, más recientemente, la preocupación por ser fotografiado o grabado sin consentimiento, han añadido razones prácticas nuevas para replantearse un hábito centenario.`,
`La tradición de decorar las ventanas tiene incluso un nombre informal en neerlandés —*etaleren*, tomado de la palabra para "escaparate"— usado medio en broma para describir lo en serio que algunos hogares se toman disponer plantas, adornos y decoraciones de temporada en la ventana del salón para que toda la calle las admire. Agentes inmobiliarios han notado que una ventana bien cuidada puede incluso dar una impresión positiva sutil durante la venta de una casa, reforzando aún más por qué tan pocos residentes sienten la necesidad de ocultarla detrás de una tela.`
    ],
    'thailand-sacred-head': [
`Esa misma jerarquía corporal atraviesa el *wai*, el saludo tailandés con las palmas juntas, donde la altura a la que se elevan las manos —y quién inclina primero y más bajo— se calibra con precisión según la edad, el estatus y la antigüedad relativa de ambas personas. Un estudiante que saluda a un profesor, o un joven que saluda a un mayor, eleva las manos juntas notablemente más alto que al saludar a alguien de su misma edad: una pequeña repetición diaria de la misma lógica de respeto que mantiene las manos lejos de la cabeza de cualquiera.`,
`Esa reverencia hacia la cabeza conecta, además, con una de las costumbres más extendidas del budismo tailandés: el monacato temporal. Se espera que la mayoría de los hombres budistas tailandeses se ordenen monjes durante algún periodo de su vida, aunque sea solo unas semanas, y la ceremonia comienza afeitándose la cabeza por completo: un acto profundo de renuncia que solo cobra sentido del todo una vez que se entiende cuánto peso cultural y espiritual carga esa parte del cuerpo.`
    ],
    'germany-splitting-bills': [
`Algunos historiadores atribuyen la intensidad moderna de esta costumbre a las décadas de posguerra, cuando la rápida reconstrucción de Alemania Occidental se apoyó en gran medida en una narrativa cultural de responsabilidad individual y autosuficiencia: la idea de que cada persona debía responder exactamente por lo que consumía se convirtió casi en una virtud cívica, extendiéndose de forma natural desde la fábrica hasta la mesa. Explique o no del todo la costumbre, esta lectura histórica encaja perfectamente con la preferencia alemana, más amplia, por las reglas explícitas frente a las expectativas sociales tácitas.`,
`El terreno de las citas es donde la costumbre genera más debate, incluso entre los propios alemanes: mientras que dividir la cuenta entre amigos apenas se cuestiona, algunos alemanes más jóvenes han empezado a rechazar el getrennte Kasse estricto en las primeras citas, argumentando que puede sentirse transaccional en vez de romántico. Foros en línea y columnas de consejos dedicadas a las citas modernas en Alemania debaten regularmente esta cuestión, señal de que la vieja regla, aunque sigue dominando, ya no es del todo incuestionable.`
    ],
    'ethiopia-calendar': [
`La diferencia entre calendarios produjo un momento inolvidable en 2007, cuando Etiopía celebró su propio cambio de milenio: marcó el año 2000 de su calendario un pleno siete años después de que el resto del mundo ya lo hubiera hecho. El gobierno lanzó una gran campaña turística internacional en torno al evento, con un centro de convenciones construido especialmente en Adís Abeba, con la esperanza de atraer atención global sobre la singular relación del país con el tiempo.`,
`En la práctica, los etíopes manejan ambos calendarios a diario sin mayor fricción: los bancos imprimen extractos con las dos fechas, los smartphones vendidos en el país suelen incluir aplicaciones de calendario etíope por defecto junto al gregoriano, y las oficinas gubernamentales sellan documentos con fecha doble para evitar confusiones a quien trate con socios internacionales. Lejos de ser un inconveniente, la mayoría de los etíopes describe el sistema dual simplemente como la forma en que el tiempo siempre ha funcionado.`
    ],
    'italy-cappuccino-rule': [
`El bar de café italiano moderno, tal como lo conocemos, es una invención relativamente reciente: tomó forma después de 1948, cuando Achille Gaggia patentó una máquina que usaba una palanca de pistón por resorte para forzar el agua a través del café a alta presión, creando la crema que define a un espresso correcto hasta hoy. Antes de que la máquina de Gaggia se extendiera por los cafés italianos en la década de 1950, la marcada diferencia entre el café de mañana y el de tarde que existe hoy todavía no se había cristalizado del todo: la regla del capuchino, en otras palabras, es una tradición del siglo XX, no una costumbre milenaria.`,
`Nápoles tiene su propio giro particular en la cultura del café, y vale la pena conocerlo: el *caffè sospeso*, o "café suspendido", una práctica en la que un cliente paga por dos espressos pero solo se toma uno, dejando el segundo ya pagado para un desconocido que no pueda costeárselo. La costumbre, nacida en los cafés populares napolitanos a mediados del siglo XX, ha sido revivida en los últimos años por cafeterías de todo el mundo inspiradas en la idea, prueba de que la cultura del café italiano exporta mucho más que la regla del capuchino.`
    ],
    'norway-babies-outside': [
`La brecha cultural que puede generar esta costumbre saltó a la prensa internacional en 1997, cuando una madre danesa de visita en Nueva York dejó a su bebé dormido en el cochecito fuera de un restaurante, visible desde su mesa —una práctica completamente normal en su país— y fue detenida por poner en peligro a un menor. El caso ocupó titulares en Escandinavia y Estados Unidos, y se convirtió en un ejemplo de manual de cómo un hábito totalmente normal en una cultura puede parecer negligencia en otra; los cargos finalmente se retiraron.`,
`Las asociaciones pediátricas nórdicas en general siguen respaldando la siesta al aire libre en clima frío para bebés sanos, siempre que estén vestidos adecuadamente y se los vigile de cerca, aunque la mayoría de las guías actuales recomiendan usar un monitor de bebé o mantener contacto visual directo en lugar de dejar el cochecito completamente fuera de la vista. La práctica también ha despertado renovado interés académico en los últimos años, con investigadores estudiando si los beneficios reportados en el sueño se sostienen bajo condiciones controladas y no solo como percepción de los padres.`
    ],
    'china-number-four': [
`Las empresas internacionales han aprendido esta lección más de una vez por las malas: Nokia, según se reporta, evitó el número cuatro al nombrar varias líneas de teléfonos vendidas en mercados asiáticos, y otros fabricantes de electrónica han evitado discretamente números de modelo que contengan un cuatro por la misma razón. La evitación no se limita a productos de consumo: anuncios inmobiliarios, nombres de empresas e incluso números de registro corporativo se ajustan cuando es posible para esquivar el dígito de mala suerte.`,
`En el lado opuesto, los números de teléfono y las matrículas cargadas de dígitos de la suerte como el ocho pueden alcanzar precios extraordinarios en subasta: subastas de matrículas y números de teléfono en China y Hong Kong han registrado ventas de cientos de miles de dólares por números repletos de ochos, mientras que las secuencias con varios cuatros suelen venderse con descuento o quedar sin comprador. El número en sí tiene un valor de mercado real y medible: un caso poco común en que la superstición aparece directamente en una etiqueta de precio.`
    ],
    'argentina-mate-sharing': [
`Aunque el ritual se asocia sobre todo con Argentina, el mate es igual de central en la vida cotidiana de Uruguay —que de hecho tiene el consumo de mate per cápita más alto del mundo— y de Paraguay, donde se prefiere una versión fría llamada *tereré* debido al calor extremo del verano paraguayo. El sur de Brasil, en particular el estado de Río Grande do Sul, comparte la misma cultura del mate de raíz gaucha, prueba de que el ritual pertenece a una identidad regional compartida anterior a las fronteras nacionales modernas trazadas sobre ella.`,
`El mate también se volvió portátil: hoy es común ver a argentinos caminando por la calle con un mate en una mano y un termo bajo el otro brazo, cebando sobre la marcha entre trámites. Su visibilidad global recibió un impulso gracias a deportistas como el futbolista Lionel Messi y jugadores de rugby que toman mate frente a las cámaras durante torneos internacionales, convirtiendo un ritual muy local en algo que millones de aficionados extranjeros ya reconocen a simple vista, aunque nunca lo hayan probado.`
    ],
    'bhutan-happiness-index': [
`La relación de Bután con la modernidad ha sido deliberadamente gradual: la televisión e internet no se introdujeron legalmente hasta 1999, lo que lo convirtió en uno de los últimos países del mundo en conectarse a los medios de difusión globales. El entonces rey enmarcó la demora explícitamente en términos de la Felicidad Nacional Bruta, argumentando que el país necesitaba tiempo para sopesar los beneficios de la conectividad frente a su potencial de alterar la cohesión social y la cultura tradicional: un caso poco común de un gobierno frenando deliberadamente la tecnología por razones declaradas de bienestar.`,
`El relato de la felicidad también tiene un capítulo genuinamente oscuro que los críticos señalan con frecuencia: a principios de la década de 1990, Bután despojó de la ciudadanía y expulsó a decenas de miles de residentes lhotshampa, de etnia y lengua nepalí, muchos de los cuales pasaron décadas en campos de refugiados en Nepal antes de ser reasentados, sobre todo en países occidentales. Los funcionarios butaneses rara vez han abordado el episodio directamente, y sigue siendo uno de los ejemplos más claros de cómo la filosofía oficial de bienestar de un país puede convivir de forma incómoda con fallos reales de derechos humanos.`
    ],
    'russia-no-smiling': [
`Algunos investigadores atribuyen la intensidad moderna de esta costumbre a las dificultades de la era soviética, cuando mostrar en público una positividad sin motivo claro podía parecer ingenuo o incluso sospechoso en un sistema definido por la escasez, la vigilancia y las privaciones: sonreír sin una razón clara y honesta simplemente no encajaba con la realidad cotidiana de generaciones enteras de rusos. Ese trasfondo histórico reforzó creencias populares más antiguas sobre el significado de la sonrisa, endureciendo un patrón cultural que persistió mucho después de que desapareciera el sistema político que lo moldeó.`,
`Dicho esto, la costumbre está cambiando visiblemente en un ámbito muy concreto: la atención al cliente. Desde la década de 1990, a medida que marcas occidentales de retail, hostelería y aerolíneas se expandieron en Rusia, muchas empresas empezaron a entrenar explícitamente a su personal para sonreír a los clientes como parte de estándares internacionales de servicio, creando una división curiosa donde una camarera o auxiliar de vuelo puede sonreír de forma profesional mientras un desconocido en la misma calle jamás lo haría sin una razón real: dos códigos distintos para el mismo gesto, funcionando en paralelo.`
    ],
    'portugal-codfish': [
`Uno de los platos de bacalao más queridos, el *bacalhau à Brás* —bacalao desmenuzado mezclado con patata paja frita, huevo revuelto y aceitunas negras—, se dice que fue inventado en el barrio de Bairro Alto, en Lisboa, por un tabernero conocido solo como "Brás", en algún momento del siglo XIX. El plato se ha vuelto tan omnipresente que la mayoría de los hogares portugueses tiene su propia variante familiar, y las disputas sobre cuál es la versión "correcta" siguen siendo un tema de debate genuinamente popular en la mesa.`,
`La ironía moderna de la obsesión portuguesa con el bacalao es más profunda de lo que la mayoría de los comensales imagina: la sobrepesca colapsó tan severamente las poblaciones de bacalao del Atlántico a lo largo del siglo XX que Portugal hoy importa prácticamente todo el bacalao que consume, casi por completo desde Noruega e Islandia. El plato nacional que define a un país, en otras palabras, depende por completo de un pescado capturado a miles de kilómetros en aguas ajenas: una cadena de suministro que se ha mantenido estable durante siglos pese a guerras, dictaduras y el colapso de la propia flota pesquera histórica de Portugal.`
    ],
    'philippines-big-families': [
`Una de las expresiones cotidianas más visibles de esta devoción familiar es la caja *balikbayan*: grandes cajas de cartón llenas de productos, golosinas y regalos que los trabajadores filipinos en el extranjero envían a casa, a veces con meses de antelación a una visita, para parientes de toda la familia extendida. Existen negocios enteros dedicados solo a consolidar y enviar estas cajas de forma económica, y su llegada suele tratarse como un pequeño evento familiar en sí mismo, abierto en conjunto con verdadera emoción por el chocolate extranjero, zapatos de marca o vitaminas que en Filipinas resultan más caros.`,
`La cultura filipina de padrinazgo, o *compadrazgo*, lleva el principio de familia extendida todavía más lejos: es común que un bautizo o una boda tengan no uno o dos padrinos, sino una docena o más, cada uno con la expectativa de jugar un papel activo en la vida del niño o de la pareja de ahí en adelante. Lejos de ser una formalidad simbólica, aceptar ser padrino conlleva obligaciones sociales reales y duraderas: otro hilo más en la densa red de apoyo mutuo que define la vida familiar filipina.`
    ],
    'switzerland-punctual-trains': [
`La ingeniería detrás de esta precisión se aprecia mejor en la estación central de Zúrich, Zúrich HB, uno de los nudos ferroviarios más concurridos de Europa, donde decenas de trenes llegan y salen dentro de los mismos minutos cada hora, calculados para que los pasajeros puedan cruzar el andén y tomar un tren de conexión con apenas dos o tres minutos de margen. Ese nivel de sincronización exige planificar los trenes no como rutas individuales, sino como un único sistema nacional interconectado, recalculado al segundo cada vez que una sola línea cambia su horario.`,
`El contraste con la vecina Alemania suele citarse como la prueba más clara de cuánto importan aquí la cultura y la inversión: Deutsche Bahn, la red ferroviaria nacional alemana, lleva años lidiando con retrasos crónicos y una infraestructura rezagada pese a operar en un país con una riqueza y capacidad de ingeniería comparables. Tanto comentaristas suizos como alemanes suelen señalar esta comparación como prueba de que la puntualidad es una decisión sostenida con financiamiento constante y expectativa cultural, no un subproducto automático de ser un país rico y ordenado.`
    ],
    'morocco-haggling': [
`El té de menta que se ofrece durante la negociación tiene su propio apodo entre visitantes e incluso algunos marroquíes: "whisky bereber", un guiño juguetón a lo central que es esta bebida en la hospitalidad de un país donde el alcohol tiene mucha menos presencia en la vida social. Preparado con té verde, generosos puñados de menta fresca y una cantidad notable de azúcar, y servido tradicionalmente desde cierta altura para crear una ligera espuma, el ritual del té no es solo una táctica de venta: rechazarlo de plano, incluso sin intención de comprar nada, puede sentirse como un pequeño desaire social.`,
`El Marruecos moderno funciona cada vez más con dos sistemas comerciales paralelos: supermercados de precio fijo, centros comerciales y cadenas de tiendas, especialmente comunes en los barrios más nuevos de Casablanca y Rabat, operan exactamente igual que sus equivalentes europeos, sin regateo esperado ni bienvenido. Los zocos tradicionales y los comercios independientes, en cambio, siguen funcionando casi por completo mediante negociación. Los marroquíes jóvenes y urbanos se mueven con fluidez entre ambos sistemas, ajustando sus expectativas al instante según el tipo de local en el que entran.`
    ],
    'iceland-no-surnames': [
`El Comité de Nombres de Islandia, el Mannanafnanefnd, no se limita a aprobar nombres nuevos automáticamente: rechaza activamente propuestas que no se ajustan a la gramática y ortografía islandesas, un proceso que ha llegado a la prensa internacional en más de una ocasión. Algunos padres han llevado al comité a juicio por nombres rechazados, y en un caso notable de 2013, una adolescente llamada Blær ("brisa suave") ganó una demanda para poder usar legalmente ese nombre por primera vez, después de que las autoridades lo hubieran considerado inválido gramaticalmente para una niña.`,
`La cultura de llamarse solo por el nombre de pila llega tan lejos que se aplica incluso en la cúspide: los islandeses suelen referirse a su presidente o primer ministro solo por su nombre de pila, tanto en contextos oficiales como en la conversación cotidiana, sin que eso se perciba como una falta de respeto como podría ocurrir en otros lugares. Es una señal pequeña pero reveladora de hasta qué punto el sistema patronímico moldea no solo cómo se nombra a los islandeses, sino lo plana e informal que tiende a sentirse, en comparación, toda la jerarquía social del país.`
    ],
    'greece-breaking-plates': [
`La exclamación "¡Opa!", gritada en el momento en que un plato se rompe o un bailarín salta, se ha convertido en una de las exportaciones culturales más reconocibles de Grecia, en gran parte gracias a los restaurantes de la diáspora griega en Estados Unidos, Australia y Europa que mantuvieron vivo el espíritu de romper platos —a veces literalmente, a veces con el sustituto más seguro de flores y servilletas— mucho después de que la práctica se desvaneciera en el día a día del propio país. Para mucha gente fuera de Grecia, "¡Opa!" es la palabra que más asocian con la cultura griega, completamente desconectada de su contexto ritual original.`,
`Las variaciones regionales añaden más matices a la costumbre: en Creta, los disparos festivos a veces acompañan bodas y bautizos en zonas rurales en lugar de, o junto con, romper platos, mientras que en Chipre, un espíritu similar de celebración exuberante se conoce como *glentia*, con sus propias costumbres locales en torno a la música, el baile y la alegría comunitaria. En todo el mundo de habla griega, el ritual concreto cambia de isla en isla, pero el impulso de fondo —que la alegría verdadera exige una salida física y compartida— se mantiene notablemente constante.`
    ],
    'singapore-chewing-gum-ban': [
`La prohibición del chicle es, en realidad, solo la entrada más famosa de una lista mucho más larga de normas que le ganaron a Singapur su apodo medio en broma de "la ciudad de las multas": comer o beber en el metro puede costar una multa de varios cientos de dólares singapurenses, llevar durián en el transporte público está prohibido directamente por su olor notoriamente intenso, y cruzar fuera del paso peatonal, no descargar la cadena de un baño público o dar de comer a las palomas pueden técnicamente acarrear una multa. En conjunto, estas normas reflejan la misma filosofía de fondo que la prohibición del chicle: el espacio público se trata como un recurso compartido que vale la pena proteger mediante reglas estrictas y aplicadas de forma constante.`,
`La prohibición del chicle se volvió un símbolo tan conocido de la rigidez singapurense que aparece con regularidad en medios internacionales y comedia como abreviatura de la reputación de orden del país, a menudo exagerada hasta la falsa afirmación de que masticar chicle en sí, y no solo su venta, es ilegal. Funcionarios de Singapur han salido públicamente en alguna ocasión a matizar las versiones más exageradas de la historia, señalando que la norma real es mucho más limitada de lo que sugiere su fama mundial, aunque el país claramente ha hecho las paces con quedarse con la broma.`
    ],
    'peru-guinea-pig': [
`Perú es, por un margen amplio, el mayor productor y consumidor de cuy como alimento en el mundo, criando un estimado de 22 millones de ejemplares al año, sobre todo en pequeñas granjas familiares repartidas por los Andes. En las últimas décadas, algunos productores han intentado modernizar la crianza de cuy e incluso explorado mercados de exportación hacia comunidades peruanas en Estados Unidos y Europa, aunque la asociación persistente del animal con las mascotas en la mayor parte del mundo ha limitado su atractivo como producto de exportación fuera de nichos especializados o nostálgicos.`,
`La tradición tampoco es exclusivamente peruana: Ecuador y Bolivia comparten la misma herencia culinaria andina, cada uno con sus propias preparaciones y nombres regionales —el *cuy* ecuatoriano se parece mucho a la versión peruana, mientras que algunas comunidades bolivianas prefieren otros condimentos y métodos de cocción—. En los tres países, el papel del cuy se remonta a la misma historia de domesticación preincaica, lo que lo convierte en uno de los animales de granja más antiguos criados de forma continua en América, anterior en miles de años a la llegada de gallinas, cerdos o ganado vacuno.`
    ],
    'sweden-fika': [
`El fika tiene incluso su propio día no oficial en el calendario nacional: el 4 de octubre se celebra en toda Suecia como *Kanelbullens dag*, el "Día del Rollo de Canela", creado en 1999 por una asociación de panaderos para promocionar el clásico pastelito del fika. Lo que empezó como una campaña de marketing se ha convertido en una fijación cultural genuina, con cafeterías, oficinas y panaderos caseros de todo el país celebrando el día con una ronda extra de rollos de canela: prueba de lo fácil que una idea comercial puede arraigar cuando encaja perfectamente en un ritual ya querido.`,
`El fika suele mencionarse en la misma frase que el concepto danés de *hygge*, y ambos se agrupan internacionalmente como una genérica "calidez escandinava", pero no son exactamente lo mismo. El hygge apunta a una sensación más amplia —velas, mantas, una sensación de calidez y contento que puede darse a solas o acompañado, en cualquier momento—. El fika es más concreto y social: una pausa programada, casi siempre compartida, construida alrededor de un café y un dulce pequeño, con sus propias reglas no escritas sobre cuándo y cómo ocurre durante la jornada laboral.`
    ]
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { EXPANSIONS };
}
