// tools/tips.js
// "What to know if you visit" section per article: one intro sentence +
// 5 practical, actionable tips. Genuinely useful content, not filler.
// Regenerated by tools/apply-tips-extra.js from tips.js + tips-extra.js.
// LINKS is locale-independent (same two related slugs for EN and ES);
// generate.js resolves each slug to that locale's actual article title.
'use strict';

const LINKS = {
  'japan-nose-blowing': ['south-korea-age-system', 'thailand-sacred-head'],
  'india-sacred-cow': ['bhutan-happiness-index', 'peru-guinea-pig'],
  'finland-sauna-queue': ['sweden-fika', 'norway-babies-outside'],
  'south-korea-age-system': ['japan-nose-blowing', 'china-number-four'],
  'france-restaurant-bill': ['italy-cappuccino-rule', 'germany-splitting-bills'],
  'mexico-day-of-the-dead': ['peru-guinea-pig', 'argentina-mate-sharing'],
  'netherlands-no-curtains': ['germany-splitting-bills', 'iceland-no-surnames'],
  'thailand-sacred-head': ['japan-nose-blowing', 'singapore-chewing-gum-ban'],
  'germany-splitting-bills': ['netherlands-no-curtains', 'switzerland-punctual-trains'],
  'ethiopia-calendar': ['morocco-haggling', 'bhutan-happiness-index'],
  'italy-cappuccino-rule': ['france-restaurant-bill', 'greece-breaking-plates'],
  'norway-babies-outside': ['finland-sauna-queue', 'sweden-fika'],
  'china-number-four': ['south-korea-age-system', 'singapore-chewing-gum-ban'],
  'argentina-mate-sharing': ['peru-guinea-pig', 'mexico-day-of-the-dead'],
  'bhutan-happiness-index': ['india-sacred-cow', 'ethiopia-calendar'],
  'russia-no-smiling': ['germany-splitting-bills', 'iceland-no-surnames'],
  'portugal-codfish': ['italy-cappuccino-rule', 'greece-breaking-plates'],
  'philippines-big-families': ['mexico-day-of-the-dead', 'argentina-mate-sharing'],
  'switzerland-punctual-trains': ['germany-splitting-bills', 'netherlands-no-curtains'],
  'morocco-haggling': ['ethiopia-calendar', 'france-restaurant-bill'],
  'iceland-no-surnames': ['finland-sauna-queue', 'netherlands-no-curtains'],
  'greece-breaking-plates': ['italy-cappuccino-rule', 'portugal-codfish'],
  'singapore-chewing-gum-ban': ['thailand-sacred-head', 'china-number-four'],
  'peru-guinea-pig': ['argentina-mate-sharing', 'india-sacred-cow'],
  'sweden-fika': ['finland-sauna-queue', 'norway-babies-outside']
};

const TIPS = {
  en: {
    'japan-nose-blowing': {
      intro: `If you're traveling to Japan, a few small habits will save you some sideways glances:`,
      tips: [
        `Carry tissues, but step away to use them — a restroom, a stairwell, or even just turning to face a wall works.`,
        `If you're sick, wear a surgical mask; it's expected, not embarrassing, and pharmacies sell them everywhere.`,
        `Don't feel obligated to stifle a cold sniffle completely — quiet sniffling is far more acceptable than a loud honk.`,
        `On trains and in offices, treat any loud bodily sound (yawning loudly, talking on the phone) with the same caution as nose-blowing.`,
        `Locals rarely explain the rule aloud — you're expected to notice and adapt, which is exactly how most Japanese social norms get passed on.`
      ]
    },
    'india-sacred-cow': {
      intro: `A few things are worth knowing before you find yourself sharing a street with a cow in India:`,
      tips: [
        `Never touch, shoo, or honk aggressively at a cow blocking traffic — patience is the expected, and safest, response.`,
        `Beef is illegal to sell or consume in several states; check local rules before ordering meat, especially outside big cities.`,
        `If you want to interact respectfully, many temples and gaushalas welcome visitors who bring vegetables or fodder to offer.`,
        `Buffalo meat is a different matter entirely and widely available — don't confuse the two animals when discussing food.`,
        `If you're unsure how to react to a cow blocking your path, just watch what nearby locals do — patience is universal here.`
      ]
    },
    'finland-sauna-queue': {
      intro: `A quick primer before your first Finnish sauna:`,
      tips: [
        `Nudity is standard in traditional Finnish saunas — swimwear is often seen as unhygienic, though mixed public saunas usually require it.`,
        `Bring your own towel to sit on; it's considered basic hygiene etiquette.`,
        `Don't talk business or gossip loudly — keep your voice down, even among friends.`,
        `If you're invited to a private sauna, it's a genuine sign of trust — treat the invitation accordingly.`,
        `Public saunas often have separate men's and women's sessions or days — check the schedule before assuming it's mixed.`,
        `Even in winter, jumping into a frozen lake through a cut ice hole (avanto) after the sauna is a genuine, if extreme, local tradition worth trying once.`
      ]
    },
    'south-korea-age-system': {
      intro: `A few pointers if age comes up in conversation in Korea:`,
      tips: [
        `When asking a Korean person their age, expect they may need a second to think about which system to answer with.`,
        `Officially, always use international age for anything legal — contracts, ID checks, alcohol purchases.`,
        `Understand that someone's stated age can affect how formally you should speak to them in Korean — age still shapes honorifics.`,
        `Don't be surprised if older relatives still casually reference "Korean age" out of habit.`,
        `Apps and official ID cards now display international age by default, so when in doubt, that's the number that counts.`,
        `Birthdays are still celebrated on the actual calendar date each year, regardless of which age-counting system is being discussed that day.`
      ]
    },
    'france-restaurant-bill': {
      intro: `Dining out in France goes more smoothly with these in mind:`,
      tips: [
        `Never snap your fingers or wave frantically for the check — make eye contact and calmly ask, "L'addition, s'il vous plaît."`,
        `Expect the meal to take ninety minutes to two hours; rushing signals you didn't enjoy it.`,
        `Tipping isn't expected since service is included, though rounding up or leaving small change is appreciated.`,
        `If you need to leave quickly, say so upfront when seated — most waitstaff will happily adjust the pace.`,
        `Reservations are common even at casual bistros — book ahead for dinner, especially on weekends.`,
        `It's completely normal to linger at the table long after finishing dessert — no one will rush you to free it up for the next guests.`
      ]
    },
    'mexico-day-of-the-dead': {
      intro: `If you're around for Día de Muertos, a little care goes a long way:`,
      tips: [
        `If invited to a family ofrenda, ask before touching or photographing personal items — some are deeply private.`,
        `Marigolds (cempasúchil) are traditional; bringing a small bouquet as a guest is a thoughtful gesture.`,
        `Avoid dressing as a "sexy" Catrina costume for street parties — many Mexicans find the trivialization disrespectful.`,
        `Public celebrations in Oaxaca, Mixquic, and Pátzcuaro welcome respectful visitors, but arrive prepared for a solemn, not spooky, atmosphere.`,
        `November 1st traditionally honors deceased children, and November 2nd honors adults — knowing the distinction shows real cultural awareness.`
      ]
    },
    'netherlands-no-curtains': {
      intro: `A few notes on navigating Dutch windows gracefully:`,
      tips: [
        `Don't stop and stare into a lit window, even if it's technically visible from the sidewalk — a glance is fine, lingering isn't.`,
        `If you're renting or buying a home, expect landlords to view uncovered windows as completely normal, not a red flag.`,
        `Photographing private homes' interiors from the street, even accidentally in the background, can be considered rude — ask first if unsure.`,
        `Bedrooms are the exception: expect curtains there even in the most transparent Dutch households.`,
        `If you do want privacy in a Dutch-style home, sheer curtains that let light through while softening the view are a common compromise.`,
        `Many Dutch families leave a lamp on in the front room specifically so the window looks inviting to passersby after dark.`
      ]
    },
    'thailand-sacred-head': {
      intro: `A short checklist for getting the body-language rules right in Thailand:`,
      tips: [
        `Never touch anyone's head, including children's, even affectionately.`,
        `Keep your feet pointed away from people, Buddha images, and altars whenever seated.`,
        `Step over doorway thresholds rather than on them — many Thai homes believe spirits live there.`,
        `When receiving or giving something to a monk, use both hands or place items on a cloth — direct hand-to-hand contact with women is traditionally avoided.`,
        `Even joking about touching someone's head, like threatening to pat it, can make people visibly uncomfortable — skip the joke entirely.`
      ]
    },
    'germany-splitting-bills': {
      intro: `Splitting a bill in Germany goes smoothly if you know this:`,
      tips: [
        `When the waiter asks "zusammen oder getrennt?" (together or separate?), it's completely normal to say separate, even on a first date.`,
        `Have small bills and coins ready — exact change speeds up the getrennte Kasse process considerably.`,
        `Don't insist on paying for someone else without a clear occasion; it can come across as presumptuous rather than generous.`,
        `For group trips, apps like Splitwise are widely used and expected for settling shared costs.`,
        `If you're the one who suggested the outing, it's fine to offer to pay first — but don't be surprised if others insist on splitting anyway.`,
        `Restaurants that only accept cash are still common, so carrying enough for your exact share is worth planning ahead.`,
        `This precision extends to splitting taxi fares and group gifts too — nothing is ever assumed to be "close enough."`
      ]
    },
    'ethiopia-calendar': {
      intro: `Planning around two calendars in Ethiopia is easy once you know this:`,
      tips: [
        `Double-check dates on official documents, flight bookings, and visas — confirm whether they're listed in the Ethiopian or Gregorian calendar.`,
        `Ethiopian New Year (Enkutatash) falls in September — a lovely time to visit for festivities and blooming fields.`,
        `Ethiopian time also starts at dawn, so when locals say "seven o'clock," clarify whether they mean local or international time.`,
        `Business meetings usually run on Gregorian time for international clarity, but cultural events often follow the Ethiopian calendar.`,
        `If someone quotes their age or a historical date and it sounds off, ask which calendar they're using before assuming a translation error.`,
        `The 13th month, Pagumē, is a great trivia fact to bring up with locals — most enjoy explaining it to curious visitors.`
      ]
    },
    'italy-cappuccino-rule': {
      intro: `A few pointers for ordering coffee like a local in Italy:`,
      tips: [
        `Order espresso or macchiato after any meal — cappuccino is safe only before noon.`,
        `Standing at the bar (al banco) is cheaper than sitting at a table — ask "al banco?" if budget matters.`,
        `No one will actually stop you from breaking the rule, but expect a knowing smile from the barista.`,
        `If you love milky coffee any time of day, order a "caffè latte" quietly and no one will bat an eye outside the most traditional spots.`,
        `Ordering a "cappuccino scuro" (extra strong) or "cappuccino chiaro" (extra light) at breakfast is a completely normal customization, any time before noon.`
      ]
    },
    'norway-babies-outside': {
      intro: `If you're a visiting parent curious to try it, keep this in mind:`,
      tips: [
        `If visiting Nordic friends with a baby, don't be alarmed if they suggest a nap outside — ask about their specific safety routine to understand it.`,
        `Dress the baby in weatherproof layers and use a sleeping bag rated for outdoor use.`,
        `Always keep the stroller within sight or use a baby monitor, even in a trusted neighborhood.`,
        `This practice is calibrated to Nordic winters — don't assume it transfers directly to much colder or more extreme climates without local guidance.`,
        `Many Nordic strollers are specifically designed with insulated bassinets rated for sub-zero naps — a regular stroller isn't automatically suited for the practice.`,
        `Daycare centers that specialize in outdoor napping usually have staff checking on sleeping babies every 15 to 20 minutes as standard practice.`
      ]
    },
    'china-number-four': {
      intro: `A few practical notes if you're doing business or house-hunting in China:`,
      tips: [
        `Don't be surprised by missing 4th, 14th, or 24th floors in hotels and offices across China, Hong Kong, and Taiwan.`,
        `Avoid gifting items in sets of four; stick to sets of eight, six, or nine for special occasions.`,
        `License plates and phone numbers with lots of 8s cost more — budget accordingly if you're settling locally.`,
        `This superstition is cultural, not universal law — most people won't be offended if a foreigner doesn't fully observe it, but noticing it shows respect.`,
        `If you're ever unsure, simply ask a local colleague or friend — most are happy to explain which numbers to avoid in a given context.`,
        `Even elevator button panels sometimes relabel the 13th floor as 12A, showing the superstition extends beyond just the number four.`,
        `Wedding gift envelopes, in particular, almost always contain amounts ending in eight or six, never four.`
      ]
    },
    'argentina-mate-sharing': {
      intro: `If someone hands you a mate, here's how to do it right:`,
      tips: [
        `If offered mate, drink the whole thing before handing it back — leaving liquid is considered impolite.`,
        `Don't stir the bombilla (straw) or move it once placed — it disrupts the brew for the next person.`,
        `Bringing your own bombilla to a group gathering is increasingly common and totally acceptable.`,
        `Saying "gracias" when you hand the mate back signals you're done for the round — stay silent if you want more.`,
        `It's fine to politely decline mate altogether at the start — just say so clearly, rather than accepting and leaving it undrunk.`
      ]
    },
    'bhutan-happiness-index': {
      intro: `Planning a trip to Bhutan? A few practicalities to know:`,
      tips: [
        `Bhutan requires a daily tourist fee for most visitors — budget for it as part of your trip cost, not an optional add-on.`,
        `Photography inside monasteries and temples is often restricted — always ask before raising your camera.`,
        `Respect the dress code at religious sites: cover shoulders and knees, and remove shoes before entering.`,
        `Independent trekking is limited; most visits require a licensed guide, which also supports the low-impact tourism model.`,
        `Altitude sickness is a real concern in mountain regions — build acclimatization days into your itinerary rather than rushing between high-altitude sites.`
      ]
    },
    'russia-no-smiling': {
      intro: `A few things that help when reading social cues in Russia:`,
      tips: [
        `Don't take a lack of smiles personally — it isn't coldness, it's cultural default, and warmth shows up once you're introduced properly.`,
        `Save your biggest smiles for people you actually know; smiling too much at strangers can read as insincere.`,
        `In service settings (hotels, tourist-facing restaurants), staff may smile more as part of international training — that's a different context.`,
        `A genuine laugh or shared joke often breaks the ice faster than a friendly smile alone.`,
        `Formal greetings (a firm handshake, direct eye contact) are taken seriously — treat the initial introduction with more formality than you might elsewhere.`
      ]
    },
    'portugal-codfish': {
      intro: `A few tips for exploring Portugal's bacalhau culture:`,
      tips: [
        `Try at least three different bacalhau preparations during a visit — locals genuinely take pride in the variety.`,
        `Bacalhau is traditionally a Christmas Eve dish — if visiting in December, ask about family recipes.`,
        `Despite looking intimidating dried and salted in shops, it's fully rehydrated and mild-tasting once cooked properly.`,
        `Pair it with a local vinho verde for the classic combination Portuguese diners favor.`,
        `If a dish looks unfamiliar, just ask — Portuguese servers are generally proud to explain the dozens of ways bacalhau can be prepared.`,
        `Restaurants sometimes serve a small unrequested appetizer (couvert) before the meal — you can decline it without offense if you'd rather not pay for it.`
      ]
    },
    'philippines-big-families': {
      intro: `If you're spending time with a Filipino family, a few things help:`,
      tips: [
        `Expect gatherings to include a wide circle of relatives — don't be surprised by dozens of "aunts" and "uncles" who aren't blood relations.`,
        `If invited to a fiesta or baptism, bringing a small gift for the family is appreciated, even as a guest of a guest.`,
        `Sending gifts home is a deeply respected form of care — don't undervalue the balikbayan box tradition if you're gifting Filipino friends abroad.`,
        `Being asked to be a godparent is an honor with real, ongoing responsibilities — think it through before accepting.`,
        `Elders are typically greeted with "mano," pressing their hand gently to your forehead — a small gesture that goes a long way with Filipino families.`
      ]
    },
    'switzerland-punctual-trains': {
      intro: `A few tips for riding Swiss rail like a local:`,
      tips: [
        `Arrive at the platform at least two to three minutes early — Swiss trains leave exactly on time, not "around" the scheduled minute.`,
        `Trust short connection windows between trains; the system is built for them to work.`,
        `Buy a Swiss Travel Pass if you're moving between cities frequently — it covers most trains, buses, and boats.`,
        `If a train is even a few minutes late, check for a compensation claim — Swiss rail takes delays seriously enough to offer refunds.`,
        `Regional and local trains sometimes run on a slightly different punctuality standard than intercity lines — don't assume every delay is equally rare.`
      ]
    },
    'morocco-haggling': {
      intro: `A few pointers for haggling well, and enjoying it, in Morocco:`,
      tips: [
        `Start your counter-offer at roughly a third to half of the vendor's opening price, then negotiate from there.`,
        `Accepting a cup of mint tea doesn't obligate you to buy anything — it's part of the process, not a trap.`,
        `Fixed-price shops (marked "prix fixe") mean exactly that — don't try to haggle there.`,
        `Smile, stay friendly, and treat it as conversation rather than confrontation — vendors respond far better to good humor than aggressive bargaining.`,
        `If a price still feels too high after negotiating, it's perfectly fine to walk away — vendors will often call you back with a better offer.`
      ]
    },
    'iceland-no-surnames': {
      intro: `A few practicalities if you're dealing with Icelandic names:`,
      tips: [
        `Address Icelanders by their first name in both casual and formal settings — it's the norm, not overly familiar.`,
        `Don't assume family members share a last name — siblings often have different patronymics or matronymics.`,
        `Iceland's phone directory is alphabetized by first name, which is genuinely useful to know if you need to look someone up.`,
        `If filling out international forms, be patient — Icelandic naming conventions don't always fit standard "first/last name" fields.`,
        `When in doubt about how to address someone formally, simply use their first name — Icelandic has largely dropped formal address altogether.`,
        `Even official government websites and ID systems are built around the patronymic system, so don't expect a "family name" field to make sense there.`
      ]
    },
    'greece-breaking-plates': {
      intro: `If you want to join the spirit of the celebration in Greece, keep this in mind:`,
      tips: [
        `Most modern tavernas use special plaster plates for smashing — ask before you throw anything that looks like real ceramic.`,
        `Some venues charge a small fee for plate-breaking as part of the show — it's usually optional and clearly offered.`,
        `Throwing flower petals or napkins is the safer, widely accepted modern alternative if you want to join the spirit of "kefi."`,
        `If attending a real family wedding, follow the lead of locals rather than assuming plate-smashing is guaranteed to happen.`,
        `Weddings and baptisms are the most likely places to see the tradition today, more than everyday tavernas — manage your expectations accordingly.`,
        `If you're hosting your own celebration and want authentic plates for smashing, some specialty shops still sell inexpensive ceramics made specifically for the purpose.`
      ]
    },
    'singapore-chewing-gum-ban': {
      intro: `A few practical facts before you pack your gum for Singapore:`,
      tips: [
        `You can bring gum for personal use into Singapore — what's actually restricted is selling or importing it commercially.`,
        `Littering fines are steep and enforced — that applies to gum wrappers as much as anything else.`,
        `Nicotine or dental gum is legally available at pharmacies with ID, if you need it for health reasons.`,
        `Beyond gum, familiarize yourself with Singapore's other everyday fines (jaywalking, eating on the MRT) before you travel.`,
        `Customs officials rarely check for personal-use gum specifically — the rule is aimed at commercial import and sale, not tourists' pockets.`
      ]
    },
    'peru-guinea-pig': {
      intro: `A few tips for trying cuy for the first time in Peru:`,
      tips: [
        `Cuy is typically served whole, bone-in — ask your server for guidance on how to eat it if it's your first time.`,
        `It's considered a special-occasion dish, so trying it at a local festival or family event offers the most authentic version.`,
        `If you're squeamish, note that flavor and texture are often compared to rabbit or dark-meat chicken.`,
        `Guinea pigs sold as pets abroad are a completely different context — no need to feel conflicted ordering cuy while traveling in Peru.`,
        `Many high-end Lima restaurants now serve gourmet, deconstructed versions of cuy for travelers curious to try it in a more familiar presentation.`
      ]
    },
    'sweden-fika': {
      intro: `A few pointers for fitting into Swedish fika culture:`,
      tips: [
        `Say yes if a Swedish colleague invites you to fika — declining repeatedly can read as standoffish.`,
        `It's normal for fika to happen twice a day in Swedish workplaces — treat it as part of the schedule, not a distraction from it.`,
        `Cinnamon buns (kanelbullar) are the classic choice, but any coffee-and-pastry combination fits the ritual.`,
        `Fika conversations are usually kept light — save serious work talk for the meeting room.`,
        `Solo fika is also completely normal — don't assume you need company to justify stepping away for coffee and a pastry.`
      ]
    }
  },

  es: {
    'japan-nose-blowing': {
      intro: `Si vas a viajar a Japón, estos hábitos te evitarán más de una mirada de reojo:`,
      tips: [
        `Lleva pañuelos, pero aléjate para usarlos: un baño, una escalera o simplemente girarte hacia una pared funciona.`,
        `Si estás resfriado, usa mascarilla quirúrgica; se espera, no es vergonzoso, y se vende en cualquier farmacia.`,
        `No sientas que debes contener por completo un resfriado: sorber en silencio es mucho más aceptable que sonarte fuerte.`,
        `En trenes y oficinas, trata cualquier sonido corporal fuerte (bostezar alto, hablar por teléfono) con la misma cautela que sonarte la nariz.`,
        `Los locales rara vez explican la regla en voz alta: se espera que la notes y te adaptes, así es como se transmiten la mayoría de las normas sociales japonesas.`
      ]
    },
    'india-sacred-cow': {
      intro: `Antes de encontrarte compartiendo una calle con una vaca en India, conviene saber esto:`,
      tips: [
        `Nunca toques, ahuyentes o le pites agresivamente a una vaca que bloquea el tráfico: la paciencia es la respuesta esperada, y más segura.`,
        `La venta y el consumo de carne de res es ilegal en varios estados; consulta las normas locales antes de pedir carne, sobre todo fuera de las grandes ciudades.`,
        `Si quieres interactuar con respeto, muchos templos y gaushalas reciben con gusto a visitantes que llevan verduras o forraje para ofrecer.`,
        `La carne de búfalo es un asunto completamente distinto y está ampliamente disponible: no confundas a los dos animales al hablar de comida.`,
        `Si no sabes cómo reaccionar ante una vaca que bloquea tu camino, simplemente observa qué hacen los locales cercanos: la paciencia es universal aquí.`
      ]
    },
    'finland-sauna-queue': {
      intro: `Una guía rápida antes de tu primera sauna finlandesa:`,
      tips: [
        `La desnudez es lo habitual en las saunas finlandesas tradicionales — el bañador suele verse como poco higiénico, aunque las saunas públicas mixtas normalmente sí lo exigen.`,
        `Lleva tu propia toalla para sentarte encima; se considera una norma básica de higiene.`,
        `No hables de negocios ni cotillees en voz alta, ni siquiera entre amigos.`,
        `Si te invitan a una sauna privada, es una señal genuina de confianza: trata la invitación en consecuencia.`,
        `Las saunas públicas suelen tener sesiones o días separados para hombres y mujeres: consulta el horario antes de asumir que es mixta.`,
        `Incluso en invierno, saltar a un lago congelado a través de un agujero cortado en el hielo (avanto) después de la sauna es una tradición local genuina, aunque extrema, que vale la pena probar una vez.`
      ]
    },
    'south-korea-age-system': {
      intro: `Algunos apuntes si la edad sale en la conversación en Corea:`,
      tips: [
        `Si le preguntas la edad a alguien coreano, es posible que necesite un segundo para pensar con qué sistema responderte.`,
        `Oficialmente, usa siempre la edad internacional para cualquier trámite legal: contratos, identificación, compra de alcohol.`,
        `Ten en cuenta que la edad declarada de alguien puede afectar cómo debes hablarle formalmente en coreano: la edad sigue determinando los honoríficos.`,
        `No te sorprendas si los familiares mayores todavía mencionan casualmente la "edad coreana" por costumbre.`,
        `Las apps y los documentos de identidad oficiales ahora muestran la edad internacional por defecto, así que, en caso de duda, ese es el número que cuenta.`,
        `Los cumpleaños se siguen celebrando en la fecha real del calendario cada año, sin importar qué sistema de conteo de edad se esté discutiendo ese día.`
      ]
    },
    'france-restaurant-bill': {
      intro: `Comer fuera en Francia va mejor si tienes esto en cuenta:`,
      tips: [
        `Nunca chasquees los dedos ni hagas señas frenéticas para pedir la cuenta: haz contacto visual y pregunta con calma "L'addition, s'il vous plaît".`,
        `Espera que la comida dure entre 90 minutos y dos horas; apurarte da a entender que no la disfrutaste.`,
        `No se espera propina porque el servicio va incluido, aunque redondear o dejar el cambio pequeño se agradece.`,
        `Si necesitas salir rápido, dilo al sentarte: la mayoría del personal ajustará el ritmo con gusto.`,
        `Las reservas son habituales incluso en bistrós informales: reserva con antelación para la cena, sobre todo los fines de semana.`,
        `Es completamente normal quedarse en la mesa mucho después de terminar el postre: nadie te apurará para liberarla para los siguientes comensales.`
      ]
    },
    'mexico-day-of-the-dead': {
      intro: `Si vas a estar cerca durante el Día de Muertos, un poco de cuidado ayuda mucho:`,
      tips: [
        `Si te invitan a la ofrenda de una familia, pregunta antes de tocar o fotografiar objetos personales — algunos son profundamente íntimos.`,
        `El cempasúchil es tradicional; llevar un pequeño ramo como invitado es un gesto considerado.`,
        `Evita disfrazarte de Catrina "sexy" para las fiestas callejeras — muchos mexicanos consideran que trivializa la tradición.`,
        `Las celebraciones públicas en Oaxaca, Mixquic y Pátzcuaro reciben a visitantes respetuosos, pero prepárate para un ambiente solemne, no de terror.`,
        `El 1 de noviembre se honra tradicionalmente a los niños difuntos, y el 2 de noviembre a los adultos: conocer esa distinción demuestra verdadero interés cultural.`
      ]
    },
    'netherlands-no-curtains': {
      intro: `Algunas notas para moverte con soltura entre las ventanas holandesas:`,
      tips: [
        `No te detengas a mirar fijamente una ventana iluminada, aunque sea técnicamente visible desde la acera — un vistazo está bien, quedarte mirando no.`,
        `Si alquilas o compras una vivienda, espera que los propietarios vean las ventanas sin cortinas como algo completamente normal, no como una señal de alarma.`,
        `Fotografiar el interior de casas privadas desde la calle, aunque sea sin querer de fondo, puede considerarse de mala educación: pregunta antes si tienes dudas.`,
        `Los dormitorios son la excepción: espera cortinas ahí incluso en los hogares holandeses más transparentes.`,
        `Si de verdad buscas privacidad en una casa de estilo holandés, los visillos que dejan pasar la luz mientras suavizan la vista son un compromiso habitual.`,
        `Muchas familias holandesas dejan una lámpara encendida en el salón principal específicamente para que la ventana se vea acogedora para quienes pasan después del anochecer.`
      ]
    },
    'thailand-sacred-head': {
      intro: `Una lista rápida para acertar con el lenguaje corporal en Tailandia:`,
      tips: [
        `Nunca toques la cabeza de nadie, ni siquiera de un niño, aunque sea con cariño.`,
        `Mantén los pies alejados de las personas, las imágenes de Buda y los altares cuando estés sentado.`,
        `Pasa por encima de los umbrales de las puertas sin pisarlos: muchas casas tailandesas creen que ahí viven espíritus.`,
        `Al dar o recibir algo de un monje, usa ambas manos o coloca el objeto sobre una tela — tradicionalmente se evita el contacto directo mano a mano con mujeres.`,
        `Incluso bromear sobre tocar la cabeza de alguien, como amenazar con darle una palmadita, puede incomodar visiblemente: mejor evita esa broma por completo.`
      ]
    },
    'germany-splitting-bills': {
      intro: `Dividir la cuenta en Alemania es sencillo si sabes esto:`,
      tips: [
        `Cuando el camarero pregunte "¿zusammen oder getrennt?" (¿junto o separado?), es completamente normal decir "separado", incluso en una primera cita.`,
        `Ten billetes y monedas pequeñas a mano: el cambio exacto agiliza bastante el proceso del getrennte Kasse.`,
        `No insistas en pagarle a alguien sin una ocasión clara: puede sentirse presuntuoso en lugar de generoso.`,
        `Para viajes en grupo, apps como Splitwise son de uso habitual y esperado para saldar gastos compartidos.`,
        `Si fuiste tú quien propuso el plan, está bien ofrecerte a pagar primero, pero no te sorprendas si los demás insisten en dividir la cuenta de todas formas.`,
        `Los restaurantes que solo aceptan efectivo siguen siendo comunes, así que vale la pena planificar llevar suficiente dinero para tu parte exacta.`,
        `Esta precisión se extiende también a dividir tarifas de taxi y regalos grupales: nunca se asume que algo esté "más o menos" bien.`
      ]
    },
    'ethiopia-calendar': {
      intro: `Organizarte con dos calendarios en Etiopía es fácil si sabes esto:`,
      tips: [
        `Verifica dos veces las fechas en documentos oficiales, vuelos y visados: confirma si están en calendario etíope o gregoriano.`,
        `El Año Nuevo etíope (Enkutatash) cae en septiembre, una época preciosa para visitar por las festividades y los campos en flor.`,
        `La hora etíope también empieza al amanecer, así que si alguien dice "las siete", aclara si se refiere a la hora local o internacional.`,
        `Las reuniones de negocios suelen usar la hora gregoriana por claridad internacional, pero los eventos culturales a menudo siguen el calendario etíope.`,
        `Si alguien menciona su edad o una fecha histórica y suena raro, pregunta qué calendario está usando antes de asumir que hay un error de traducción.`,
        `El decimotercer mes, Pagumē, es un gran dato curioso para comentar con los locales: a la mayoría le encanta explicárselo a visitantes con curiosidad.`
      ]
    },
    'italy-cappuccino-rule': {
      intro: `Algunos consejos para pedir café como un local en Italia:`,
      tips: [
        `Pide espresso o macchiato después de cualquier comida: el capuchino es seguro solo antes del mediodía.`,
        `Tomarlo de pie en la barra (al banco) es más barato que sentarse en una mesa: pregunta "¿al banco?" si el presupuesto importa.`,
        `Nadie te va a detener si rompes la regla, pero espera una sonrisa cómplice del barista.`,
        `Si te encanta el café con leche a cualquier hora, pide un "caffè latte" discretamente y nadie se inmutará fuera de los lugares más tradicionales.`,
        `Pedir un "cappuccino scuro" (extra fuerte) o "cappuccino chiaro" (extra suave) en el desayuno es una personalización totalmente normal, siempre antes del mediodía.`
      ]
    },
    'norway-babies-outside': {
      intro: `Si eres un padre o madre visitante con curiosidad por probarlo, ten esto en cuenta:`,
      tips: [
        `Si visitas amigos nórdicos con un bebé, no te alarmes si sugieren una siesta al aire libre: pregunta por su rutina de seguridad concreta para entenderla.`,
        `Viste al bebé con capas resistentes al clima y usa un saco de dormir certificado para exteriores.`,
        `Mantén siempre el cochecito a la vista o usa un monitor de bebé, incluso en un barrio de confianza.`,
        `Esta práctica está calibrada para los inviernos nórdicos: no asumas que se traslada directamente a climas mucho más fríos o extremos sin orientación local.`,
        `Muchos cochecitos nórdicos están diseñados específicamente con capazos aislados aptos para siestas bajo cero: un cochecito normal no está automáticamente preparado para esta práctica.`,
        `Las guarderías especializadas en siestas al aire libre suelen tener personal que revisa a los bebés dormidos cada 15 o 20 minutos como práctica estándar.`
      ]
    },
    'china-number-four': {
      intro: `Algunas notas prácticas si haces negocios o buscas casa en China:`,
      tips: [
        `No te sorprenda la ausencia de pisos 4, 14 o 24 en hoteles y oficinas de China, Hong Kong y Taiwán.`,
        `Evita regalar objetos en grupos de cuatro; prefiere grupos de ocho, seis o nueve para ocasiones especiales.`,
        `Las matrículas y números de teléfono con muchos ochos cuestan más: ten esto en cuenta si te instalas allí.`,
        `Esta superstición es cultural, no una ley universal — a la mayoría no le ofenderá que un extranjero no la respete del todo, pero notarla demuestra respeto.`,
        `Si alguna vez tienes dudas, simplemente pregúntale a un colega o amigo local: la mayoría estará encantada de explicarte qué números evitar en cada contexto.`,
        `Incluso los paneles de botones de los ascensores a veces renombran el piso 13 como 12A, mostrando que la superstición va más allá del número cuatro.`,
        `Los sobres de regalo de boda, en particular, casi siempre contienen cantidades que terminan en ocho o seis, nunca en cuatro.`
      ]
    },
    'argentina-mate-sharing': {
      intro: `Si alguien te pasa un mate, así se hace correctamente:`,
      tips: [
        `Si te ofrecen mate, bébetelo entero antes de devolverlo: dejar líquido se considera de mala educación.`,
        `No revuelvas la bombilla ni la muevas una vez colocada: arruina la preparación para la siguiente persona.`,
        `Llevar tu propia bombilla a una reunión grupal es cada vez más común y totalmente aceptable.`,
        `Decir "gracias" al devolver el mate indica que ya no quieres más en esa ronda: quédate en silencio si quieres otro.`,
        `Está bien rechazar el mate educadamente desde el principio: solo dilo con claridad, en lugar de aceptarlo y dejarlo sin tomar.`
      ]
    },
    'bhutan-happiness-index': {
      intro: `¿Planeas un viaje a Bután? Algunas cuestiones prácticas que conviene saber:`,
      tips: [
        `Bután exige una tarifa diaria a la mayoría de los turistas: inclúyela en el presupuesto del viaje, no como un extra opcional.`,
        `La fotografía dentro de monasterios y templos suele estar restringida: pregunta siempre antes de sacar la cámara.`,
        `Respeta el código de vestimenta en sitios religiosos: cubre hombros y rodillas, y quítate los zapatos antes de entrar.`,
        `El trekking independiente es limitado; la mayoría de las visitas requieren un guía autorizado, lo que también sostiene el modelo de turismo de bajo impacto.`,
        `El mal de altura es una preocupación real en las zonas montañosas: incluye días de aclimatación en tu itinerario en lugar de apresurarte entre sitios de gran altitud.`
      ]
    },
    'russia-no-smiling': {
      intro: `Algunas claves para interpretar mejor las señales sociales en Rusia:`,
      tips: [
        `No te tomes la falta de sonrisas como algo personal: no es frialdad, es la costumbre cultural, y la calidez aparece una vez que te presentan como se debe.`,
        `Guarda tus mejores sonrisas para la gente que realmente conoces; sonreír demasiado a desconocidos puede sonar poco sincero.`,
        `En entornos de servicio (hoteles, restaurantes turísticos), el personal puede sonreír más como parte de su formación internacional: es un contexto distinto.`,
        `Una risa genuina o un chiste compartido suele romper el hielo más rápido que una sonrisa amable por sí sola.`,
        `Los saludos formales (un apretón de manos firme, contacto visual directo) se toman en serio: trata la primera presentación con más formalidad de la que usarías en otros lugares.`
      ]
    },
    'portugal-codfish': {
      intro: `Algunos consejos para explorar la cultura del bacalao en Portugal:`,
      tips: [
        `Prueba al menos tres preparaciones distintas de bacalao durante tu visita: los locales realmente se enorgullecen de la variedad.`,
        `El bacalao es tradicionalmente un plato de Nochebuena: si visitas en diciembre, pregunta por las recetas familiares.`,
        `Aunque en las tiendas se vea intimidante seco y salado, queda completamente hidratado y de sabor suave una vez cocinado correctamente.`,
        `Combínalo con un vinho verde local para la combinación clásica que prefieren los comensales portugueses.`,
        `Si un plato te resulta desconocido, simplemente pregunta: los camareros portugueses suelen estar orgullosos de explicar las decenas de formas de preparar el bacalao.`,
        `Los restaurantes a veces sirven un pequeño aperitivo no solicitado (couvert) antes de la comida: puedes rechazarlo sin ofender si prefieres no pagarlo.`
      ]
    },
    'philippines-big-families': {
      intro: `Si vas a pasar tiempo con una familia filipina, esto ayuda:`,
      tips: [
        `Espera que las reuniones incluyan un círculo amplio de familiares: no te sorprendas por decenas de "tíos" y "tías" que no son parientes de sangre.`,
        `Si te invitan a una fiesta o un bautizo, llevar un pequeño regalo para la familia se agradece, incluso siendo invitado de un invitado.`,
        `Enviar regalos a casa es una forma de cuidado muy respetada: no subestimes la tradición de la caja balikbayan si le regalas algo a amigos filipinos en el extranjero.`,
        `Que te pidan ser padrino es un honor con responsabilidades reales y duraderas: piénsalo bien antes de aceptar.`,
        `A los mayores se les suele saludar con el "mano", presionando suavemente su mano contra tu frente: un pequeño gesto que vale mucho con las familias filipinas.`
      ]
    },
    'switzerland-punctual-trains': {
      intro: `Algunos consejos para moverte en tren por Suiza como un local:`,
      tips: [
        `Llega al andén al menos 2-3 minutos antes: los trenes suizos salen exactamente a su hora, no "más o menos" al minuto previsto.`,
        `Confía en los tiempos de conexión cortos entre trenes: el sistema está diseñado para que funcionen.`,
        `Compra un Swiss Travel Pass si te mueves entre ciudades con frecuencia: cubre la mayoría de trenes, autobuses y barcos.`,
        `Si un tren llega con unos minutos de retraso, consulta si puedes reclamar una compensación: los ferrocarriles suizos se toman los retrasos en serio hasta el punto de ofrecer reembolsos.`,
        `Los trenes regionales y locales a veces tienen un estándar de puntualidad ligeramente distinto al de las líneas interurbanas: no asumas que todos los retrasos son igual de raros.`
      ]
    },
    'morocco-haggling': {
      intro: `Algunos consejos para regatear bien, y disfrutarlo, en Marruecos:`,
      tips: [
        `Empieza tu contraoferta en aproximadamente un tercio o la mitad del precio inicial del vendedor, y negocia desde ahí.`,
        `Aceptar un té de menta no te obliga a comprar nada: es parte del proceso, no una trampa.`,
        `Las tiendas de precio fijo (marcadas "prix fixe") significan exactamente eso: no intentes regatear ahí.`,
        `Sonríe, mantén un tono amistoso y trátalo como una conversación, no como una confrontación: los vendedores responden mucho mejor al buen humor que al regateo agresivo.`,
        `Si un precio te sigue pareciendo demasiado alto después de negociar, está perfectamente bien irte: los vendedores suelen llamarte de vuelta con una mejor oferta.`
      ]
    },
    'iceland-no-surnames': {
      intro: `Algunas cuestiones prácticas si tienes que lidiar con nombres islandeses:`,
      tips: [
        `Dirígete a los islandeses por su nombre de pila tanto en contextos informales como formales: es la norma, no resulta excesivamente familiar.`,
        `No asumas que los familiares comparten apellido: los hermanos suelen tener patronímicos o matronímicos distintos.`,
        `El directorio telefónico de Islandia se ordena por nombre de pila, algo genuinamente útil de saber si necesitas buscar a alguien.`,
        `Si rellenas formularios internacionales, ten paciencia: las convenciones de nombres islandesas no siempre encajan en los campos estándar de "nombre/apellido".`,
        `Si tienes dudas sobre cómo dirigirte a alguien formalmente, usa simplemente su nombre de pila: el islandés prácticamente ha eliminado el tratamiento formal.`,
        `Incluso los sitios web y sistemas de identificación del gobierno están construidos en torno al sistema patronímico, así que no esperes que un campo de "apellido" tenga sentido ahí.`
      ]
    },
    'greece-breaking-plates': {
      intro: `Si quieres sumarte al espíritu de la celebración en Grecia, ten esto en cuenta:`,
      tips: [
        `La mayoría de las tabernas modernas usan platos especiales de yeso para romper: pregunta antes de lanzar algo que parezca cerámica de verdad.`,
        `Algunos locales cobran una pequeña tarifa por romper platos como parte del espectáculo: suele ser opcional y se ofrece con claridad.`,
        `Lanzar pétalos de flores o servilletas es la alternativa moderna más segura y aceptada si quieres sumarte al espíritu del "kefi".`,
        `Si asistes a una boda familiar real, sigue el ejemplo de los locales en lugar de asumir que romper platos está garantizado.`,
        `Las bodas y los bautizos son hoy los lugares donde es más probable ver la tradición, más que en las tabernas cotidianas: ajusta tus expectativas en consecuencia.`,
        `Si organizas tu propia celebración y quieres platos auténticos para romper, algunas tiendas especializadas todavía venden cerámica económica hecha específicamente para ese propósito.`
      ]
    },
    'singapore-chewing-gum-ban': {
      intro: `Algunos datos prácticos antes de empacar tu chicle para Singapur:`,
      tips: [
        `Puedes llevar chicle para uso personal a Singapur; lo que realmente está restringido es venderlo o importarlo comercialmente.`,
        `Las multas por tirar basura son elevadas y se aplican de verdad: eso incluye los envoltorios de chicle igual que cualquier otra cosa.`,
        `El chicle de nicotina o dental está disponible legalmente en farmacias con identificación, si lo necesitas por motivos de salud.`,
        `Más allá del chicle, infórmate de las demás multas cotidianas de Singapur (cruzar fuera del paso peatonal, comer en el metro) antes de viajar.`,
        `Los funcionarios de aduanas rara vez revisan específicamente el chicle de uso personal: la norma apunta a la importación y venta comercial, no a los bolsillos de los turistas.`
      ]
    },
    'peru-guinea-pig': {
      intro: `Algunos consejos para probar el cuy por primera vez en Perú:`,
      tips: [
        `El cuy suele servirse entero, con hueso: pídele orientación al camarero sobre cómo comerlo si es tu primera vez.`,
        `Se considera un plato de ocasión especial, así que probarlo en un festival local o un evento familiar ofrece la versión más auténtica.`,
        `Si te da un poco de aprensión, ten en cuenta que su sabor y textura suelen compararse con el conejo o el pollo de carne oscura.`,
        `Los cuyes vendidos como mascotas en otros países son un contexto completamente distinto: no hace falta sentirse en conflicto al pedir cuy mientras viajas por Perú.`,
        `Muchos restaurantes de alta gama en Lima ahora sirven versiones gourmet y deconstruidas del cuy, pensadas para viajeros con curiosidad por probarlo en una presentación más familiar.`
      ]
    },
    'sweden-fika': {
      intro: `Algunos consejos para encajar en la cultura del fika sueca:`,
      tips: [
        `Di que sí si un colega sueco te invita a fika: rechazar repetidamente puede sonar distante.`,
        `Es normal que el fika ocurra dos veces al día en los trabajos suecos: trátalo como parte del horario, no como una distracción.`,
        `Los rollos de canela (kanelbullar) son la opción clásica, pero cualquier combinación de café y dulce encaja en el ritual.`,
        `Las conversaciones de fika suelen mantenerse ligeras: guarda los temas serios de trabajo para la sala de reuniones.`,
        `El fika en solitario también es completamente normal: no asumas que necesitas compañía para justificar una pausa con café y un dulce.`
      ]
    }
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TIPS, LINKS };
}
